# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamy < Formula
  desc "A CLI tool that asks a series of questions to clarify what you want to know."
  homepage "https://github.com/akihisa1210/lamy"
  version "2.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akihisa1210/lamy/releases/download/v2.0.1/lamy_2.0.1_macOS_x86_64.zip"
      sha256 "badb996270962e7c9582f4bade7b60d5733cc2ffb8d34f31cf927a5e443ed735"

      def install
        bin.install "lamy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/akihisa1210/lamy/releases/download/v2.0.1/lamy_2.0.1_linux_x86_64.zip"
      sha256 "ff718da1b92eb82190008bd00decc4b5ea46ac122a5c1b7e9800fdbd2f23e552"

      def install
        bin.install "lamy"
      end
    end
  end
end
